// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using OrderMgmt.Data;

namespace OrderMgmt.Migrations
{
    [DbContext(typeof(OrderMgmtDbContext))]
    partial class RenameSystemUserToAppUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This is intentionally minimal - migration only does a raw SQL rename
        }
    }
}
