// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using PreOrderApp.Data;

namespace PreOrderApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class RenameSystemUserToAppUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This is intentionally minimal - migration only does a raw SQL rename
        }
    }
}
